# Generated by Django 6.0.1 on 2026-02-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_monthlyinvoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monthlyinvoice",
            name="published_date",
        ),
        migrations.AddField(
            model_name="monthlyinvoice",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
