# Generated by Django 5.2.8 on 2026-01-26 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_property_authorized_users"),
        ("reservations", "0003_add_reference_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="room_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="properties.roomcategory",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="properties.room",
            ),
        ),
    ]
