# Generated by Django 6.0.1 on 2026-02-13 08:17

from django.db import migrations, models
from django.conf import settings


def update_payment_receipt_storage(apps, schema_editor):
    """
    This function updates the payment_receipt field to use R2 storage.
    Since this is a storage backend change, we don't need to modify the database schema.
    The field definition in the model already includes the storage parameter.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0005_auto_20260212_0842"),
    ]

    operations = [
        # This is a no-op migration since the storage change is handled at the model level
        # The field already has storage=r2_storage in the model definition
        migrations.RunPython(update_payment_receipt_storage, migrations.RunPython.noop),
    ]
