# Generated by Django 5.2.8 on 2026-02-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownerdashboardstats",
            name="revenue_change_percentage",
            field=models.FloatField(default=0),
        ),
    ]
