# Generated by Django 5.2.8 on 2026-02-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_ownerdashboardstats_revenue_change_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownerdashboardstats",
            name="reservation_change_percentage",
            field=models.FloatField(default=0),
        ),
    ]
