# Generated by Django 6.0.1 on 2026-01-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="owner_type",
            field=models.CharField(
                blank=True,
                choices=[("single", "Single Owner"), ("multi", "Multi Owner")],
                default="",
                max_length=10,
                null=True,
            ),
        ),
    ]
