# Generated by Django 5.2.8 on 2026-01-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_owner_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="company",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
