# Generated by Django 5.2.8 on 2026-01-16 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="emailverification",
            name="invitation_type",
            field=models.CharField(
                choices=[
                    ("verification", "Email Verification"),
                    ("owner_invitation", "Owner Invitation"),
                ],
                default="verification",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="emailverification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_verifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
