# Generated by Django 5.2.8 on 2026-01-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_emailverification_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="owner_type",
            field=models.CharField(
                blank=True,
                choices=[("single", "Single Owner"), ("multi", "Multi Owner")],
                max_length=10,
            ),
        ),
    ]
