# Generated by Django 6.0.1 on 2026-01-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_emailverification_owner_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="property_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
