# Generated by Django 5.2.8 on 2026-01-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="map_link",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
