# Generated by Django 5.2.8 on 2026-01-17 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_alter_property_map_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_occupancy", models.IntegerField()),
                ("amenities", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_categories",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
