# Generated by Django 5.2.8 on 2026-01-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_roomcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomcategory",
            name="bed_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="roomcategory",
            name="size",
            field=models.IntegerField(default=0),
        ),
    ]
