# Generated by Django 5.2.8 on 2026-01-19 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_property_created_by_alter_property_map_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="authorized_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="authorized_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
