# Generated by Django 5.2.8 on 2026-01-26 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_property_authorized_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="properties.roomcategory",
            ),
        ),
    ]
