# Generated by Django 6.0.1 on 2026-02-04 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_propertytype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertytype',
            options={'ordering': ['name'], 'verbose_name_plural': 'Property Types'},
        ),
        migrations.RemoveField(
            model_name='propertytype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='propertytype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='propertytype',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='propertytype',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='propertytype',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='propertytype',
            name='updated_at',
        ),
    ]
