# Generated by Django 5.2.8 on 2026-02-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0009_simplify_property_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertytype",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="propertytype",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="property_types/"),
        ),
    ]
