# Generated by Django 5.2.8 on 2026-02-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0010_propertytype_image_url_alter_propertytype_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertytype",
            name="image",
        ),
    ]
