# Generated by Django 5.2.8 on 2026-02-05 07:54

import reserve_at_ease.custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0011_remove_property_type_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertytype",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=reserve_at_ease.custom_storage.R2Storage(),
                upload_to="property_types/",
            ),
        ),
    ]
