# Generated by Django 5.2.8 on 2026-02-05 13:43

import reserve_at_ease.custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0012_add_property_type_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="City name", max_length=100)),
                ("country", models.CharField(default="Nigeria", max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=reserve_at_ease.custom_storage.R2Storage(),
                        upload_to="destinations/",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="External image URL (for Unsplash images)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "property_count",
                    models.IntegerField(
                        default=0, help_text="Number of properties in this destination"
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Order to display destinations"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Destinations",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
