# Generated by Django 5.2.8 on 2026-02-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0013_add_destination"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="destination",
            name="country",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="destination",
            name="property_count",
        ),
        migrations.AlterField(
            model_name="destination",
            name="name",
            field=models.CharField(help_text="City/Destination name", max_length=100),
        ),
    ]
