# Generated by Django 5.2.8 on 2026-02-05 21:03

import reserve_at_ease.custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0014_simplify_destination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyimage",
            name="image",
            field=models.ImageField(
                storage=reserve_at_ease.custom_storage.R2Storage(),
                upload_to="property_images/",
            ),
        ),
        migrations.AlterField(
            model_name="roomimage",
            name="image",
            field=models.ImageField(
                storage=reserve_at_ease.custom_storage.R2Storage(),
                upload_to="room_images/",
            ),
        ),
    ]
