# Generated by Django 6.0.1 on 2026-02-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0015_alter_propertyimage_image_alter_roomimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="External image URL (for Unsplash images) - Auto-populated from uploaded image",
                max_length=500,
                null=True,
            ),
        ),
    ]
