# Generated by Django 6.0.1 on 2026-02-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0016_alter_destination_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="image_url",
            field=models.CharField(
                blank=True,
                help_text="External image URL (for Unsplash images) - Auto-populated from uploaded image",
                max_length=500,
                null=True,
            ),
        ),
    ]
