# Generated by Django 6.0.1 on 2026-02-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0018_alter_destination_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyavailability",
            name="discount_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="propertyavailability",
            name="has_discount",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roomcategory",
            name="discount_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="roomcategory",
            name="discount_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="roomcategory",
            name="discount_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="roomcategory",
            name="has_discount",
            field=models.BooleanField(default=False),
        ),
    ]
