# Generated by Django 5.2.8 on 2026-01-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_alter_review_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyreviewsummary",
            name="rating_10_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="propertyreviewsummary",
            name="rating_6_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="propertyreviewsummary",
            name="rating_7_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="propertyreviewsummary",
            name="rating_8_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="propertyreviewsummary",
            name="rating_9_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "1 Star"),
                    (2, "2 Stars"),
                    (3, "3 Stars"),
                    (4, "4 Stars"),
                    (5, "5 Stars"),
                    (6, "6 Stars"),
                    (7, "7 Stars"),
                    (8, "8 Stars"),
                    (9, "9 Stars"),
                    (10, "10 Stars"),
                ]
            ),
        ),
    ]
