# Generated by Django 5.2.8 on 2026-01-19 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_propertyreviewsummary_rating_10_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="owner_response",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent_review",
                to="reviews.reviewresponse",
            ),
        ),
        migrations.AlterField(
            model_name="reviewresponse",
            name="review",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="response_obj",
                to="reviews.review",
            ),
        ),
    ]
